# Generated by Django 4.2.16 on 2025-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('XAF', 'Central Africa'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='XAF', max_length=3),
        ),
    ]
