version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
      - db_data:/app/db.sqlite3  # optional volume
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

volumes:
  db_data:
